// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: model_3d.proto

#include "model_3d.pb.h"
#include "model_3d.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Model3D_method_names[] = {
  "/Model3D/Convert",
  "/Model3D/Version",
};

std::unique_ptr< Model3D::Stub> Model3D::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Model3D::Stub> stub(new Model3D::Stub(channel, options));
  return stub;
}

Model3D::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Convert_(Model3D_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Version_(Model3D_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Model3D::Stub::Convert(::grpc::ClientContext* context, const ::Model& request, ::Model* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Model, ::Model, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Convert_, context, request, response);
}

void Model3D::Stub::async::Convert(::grpc::ClientContext* context, const ::Model* request, ::Model* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Model, ::Model, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, std::move(f));
}

void Model3D::Stub::async::Convert(::grpc::ClientContext* context, const ::Model* request, ::Model* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Model>* Model3D::Stub::PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::Model& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Model, ::Model, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Convert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Model>* Model3D::Stub::AsyncConvertRaw(::grpc::ClientContext* context, const ::Model& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConvertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Model3D::Stub::Version(::grpc::ClientContext* context, const ::VersionNumber& request, ::VersionNumber* response) {
  return ::grpc::internal::BlockingUnaryCall< ::VersionNumber, ::VersionNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Version_, context, request, response);
}

void Model3D::Stub::async::Version(::grpc::ClientContext* context, const ::VersionNumber* request, ::VersionNumber* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::VersionNumber, ::VersionNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, std::move(f));
}

void Model3D::Stub::async::Version(::grpc::ClientContext* context, const ::VersionNumber* request, ::VersionNumber* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::VersionNumber>* Model3D::Stub::PrepareAsyncVersionRaw(::grpc::ClientContext* context, const ::VersionNumber& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::VersionNumber, ::VersionNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Version_, context, request);
}

::grpc::ClientAsyncResponseReader< ::VersionNumber>* Model3D::Stub::AsyncVersionRaw(::grpc::ClientContext* context, const ::VersionNumber& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

Model3D::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Model3D_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Model3D::Service, ::Model, ::Model, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Model3D::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Model* req,
             ::Model* resp) {
               return service->Convert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Model3D_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Model3D::Service, ::VersionNumber, ::VersionNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Model3D::Service* service,
             ::grpc::ServerContext* ctx,
             const ::VersionNumber* req,
             ::VersionNumber* resp) {
               return service->Version(ctx, req, resp);
             }, this)));
}

Model3D::Service::~Service() {
}

::grpc::Status Model3D::Service::Convert(::grpc::ServerContext* context, const ::Model* request, ::Model* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Model3D::Service::Version(::grpc::ServerContext* context, const ::VersionNumber* request, ::VersionNumber* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


